//! Reversing `java.util.Random` from partial observations of its output.
//!
//! This is a port of the idea behind mjtb49/LattiCG, built on the exact
//! lattice machinery in [`crate::lll`].
//!
//! # The problem
//!
//! You watched one `Random` produce a sequence of values — some observed
//! exactly, some only bounded, some not observed at all — and you want every
//! seed that could have produced them. Brute force is 2^48. Lattice reduction
//! turns it into an enumeration whose cost is proportional to the number of
//! *answers*, which is usually a handful.
//!
//! # How it becomes a lattice
//!
//! Every observation ultimately says "the 48-bit LCG state at call `k` lies in
//! `[lo_k, hi_k]`". Writing `s` for the state at the first measured call, the
//! state at call `k` is
//!
//! ```text
//! state_k = s * a^(k - k_0) + c_k   (mod 2^48)
//! ```
//!
//! where `a` is the multiplier and `c_k` is the purely additive part (what the
//! generator would produce starting from state 0). So the vector of states we
//! are looking for is
//!
//! ```text
//! (s*a^0, s*a^d1, ..., s*a^dn) + (c_0, ..., c_n)   (mod 2^48)
//! ```
//!
//! The set of such vectors, over all integer `s` and all multiples of 2^48 per
//! coordinate, is exactly a lattice: generated by the row
//! `(a^0, a^d1, ..., a^dn)` together with `2^48 * e_i` for each coordinate.
//! Finding valid seeds is then "find the lattice points inside this box", once
//! the constant vector has been subtracted off.
//!
//! Two practical details matter:
//!
//! * **Axis scaling.** The box is usually far longer in some axes than others,
//!   and lattice reduction works on Euclidean length. Scaling each axis by
//!   `lcm / sideLength` turns the box into a cube first, exactly as LattiCG
//!   does; without it the reduction optimises for the wrong geometry and the
//!   enumeration explodes.
//! * **Constraints that are not intervals.** `nextInt(n)` for non-power-of-two
//!   `n` is a *modular* condition, and things like "this floor block was mossy"
//!   are the complement of an interval. Neither is a box, so they are not put
//!   in the lattice at all — they become filters applied by replaying the
//!   generator over each candidate the lattice produces. That keeps the
//!   lattice sound (it never excludes a real answer) at the cost of a few
//!   extra candidates to check.

use anyhow::{Result, bail};
use num_bigint::BigInt;
use num_rational::BigRational;
use num_traits::{One, Signed, Zero};
use rayon::prelude::*;

use crate::lll::{DEFAULT_MAX_NODES, RatMatrix, enumerate_in_box_capped};
use crate::random::{JavaRandom, MASK, MULTIPLIER};

/// One interval constraint on the LCG state at a given call index.
#[derive(Debug, Clone)]
struct StateBound {
    /// How many `next()` steps past the initial state this observation sits.
    call_index: u64,
    lo: BigInt,
    hi: BigInt,
}

/// A predicate replayed over candidate seeds, for constraints a box cannot
/// express.
struct Filter {
    /// Steps consumed from the generator before this check runs.
    at_call: u64,
    /// Number of steps the check itself consumes.
    width: u64,
    test: Box<dyn Fn(&mut JavaRandom) -> bool + Send + Sync>,
    label: String,
}

impl std::fmt::Debug for Filter {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Filter")
            .field("at_call", &self.at_call)
            .field("width", &self.width)
            .field("label", &self.label)
            .finish()
    }
}

/// Builds a system of observations about one `Random` and solves it.
#[derive(Debug, Default)]
pub struct Reverser {
    bounds: Vec<StateBound>,
    filters: Vec<Filter>,
    /// Steps consumed so far, i.e. the index of the next call.
    cursor: u64,
    /// Fraction of the seed space knowingly excluded by assuming that no
    /// `nextInt` call hit its retry branch. See [`Reverser::next_int_eq`].
    ignored_fraction: f64,
}

/// `next(31)`'s value is the top 31 bits of the state, so a bound on it
/// becomes a bound on the state by shifting.
const NEXT31_SHIFT: u32 = 17;

impl Reverser {
    pub fn new() -> Reverser {
        Reverser::default()
    }

    /// Number of interval constraints, i.e. the lattice dimension.
    pub fn dimensions(&self) -> usize {
        self.bounds.len()
    }

    /// Discards `n` calls without learning anything from them.
    pub fn skip(&mut self, n: u64) -> &mut Self {
        self.cursor += n;
        self
    }

    /// Records an interval already known to be well formed.
    ///
    /// Private because it does no checking: every public entry point validates
    /// first, and an inverted interval reaching the scaling step produces a
    /// negative side length and a silently empty answer rather than an error.
    fn push_bound(&mut self, lo: BigInt, hi: BigInt) -> &mut Self {
        debug_assert!(lo <= hi, "push_bound called with an inverted interval");
        self.cursor += 1;
        self.bounds.push(StateBound {
            call_index: self.cursor,
            lo,
            hi,
        });
        self
    }

    /// Constrains the state at the next call to `[lo, hi]` directly.
    pub fn state_in(&mut self, lo: BigInt, hi: BigInt) -> Result<&mut Self> {
        if lo > hi {
            bail!("state bound is inverted: lo {lo} is above hi {hi}");
        }
        let ceiling = BigInt::from(MASK);
        if lo.is_negative() || hi > ceiling {
            bail!("state bounds must lie in 0..=2^48-1, got {lo}..={hi}");
        }
        Ok(self.push_bound(lo, hi))
    }

    /// Constrains `next(bits)` to `[lo, hi]` inclusive.
    pub fn next_bits_in(&mut self, bits: u32, lo: u64, hi: u64) -> Result<&mut Self> {
        // Java's `next(bits)` is only defined for 1..=32; outside that the
        // shift below underflows and the interval is meaningless.
        if !(1..=32).contains(&bits) {
            bail!("next({bits}) is not a valid Java call; bits must be 1..=32");
        }
        let ceiling = (1u64 << bits) - 1;
        if lo > hi || hi > ceiling {
            bail!("next({bits}) can only return 0..={ceiling}, got {lo}..={hi}");
        }
        let shift = 48 - bits;
        Ok(self.push_bound(
            BigInt::from(lo) << shift,
            (((BigInt::from(hi)) + 1u32) << shift) - 1u32,
        ))
    }

    /// Records `nextInt(bound) == value`.
    ///
    /// For a power-of-two bound Java computes `(bound * next(31)) >> 31`,
    /// which is monotone in `next(31)` and so gives a single clean interval.
    /// For any other bound it is `next(31) % bound` with a rejection loop —
    /// a union of thousands of single points, which is not a box. Those become
    /// replay filters instead; the lattice stays sound either way.
    pub fn next_int_eq(&mut self, bound: u32, value: u32) -> Result<&mut Self> {
        if bound == 0 || value >= bound {
            bail!("nextInt({bound}) cannot return {value}");
        }
        if bound.is_power_of_two() {
            // value == (bound * next31) >> 31  <=>
            // next31 in [ceil(value * 2^31 / bound), ceil((value+1) * 2^31 / bound) - 1]
            let two31 = BigInt::from(1u64 << 31);
            let lo = div_ceil(&(BigInt::from(value) * &two31), &BigInt::from(bound));
            let hi = div_ceil(&(BigInt::from(value + 1) * &two31), &BigInt::from(bound)) - 1u32;
            self.cursor += 1;
            self.bounds.push(StateBound {
                call_index: self.cursor,
                lo: lo << NEXT31_SHIFT,
                hi: ((hi + 1u32) << NEXT31_SHIFT) - 1u32,
            });
            Ok(self)
        } else {
            // Java's `nextInt(n)` retries when `next(31)` lands in the short
            // tail that would bias the modulo, consuming an extra call. Our
            // call accounting fixes one call per observation, so we require
            // the draw to have been single-shot and exclude the retry cases
            // outright — the same trade LattiCG makes, which reports the
            // fraction it ignores rather than silently mis-indexing every
            // later constraint.
            self.ignored_fraction += bound as f64 / 2f64.powi(31);
            self.filtered_skip(1, &format!("nextInt({bound}) == {value}"), move |r| {
                let bits = r.next(31);
                let val = bits % bound as i32;
                let single_draw =
                    bits.wrapping_sub(val).wrapping_add(bound as i32 - 1) >= 0;
                single_draw && val == value as i32
            });
            Ok(self)
        }
    }

    /// Records `nextInt(bound) != value` — never a box, always a filter.
    ///
    /// Validated like [`Reverser::next_int_eq`]: an out-of-range value would
    /// otherwise register a predicate that can never fail while still
    /// consuming a call, so the observation would silently contribute nothing.
    pub fn next_int_ne(&mut self, bound: u32, value: u32) -> Result<&mut Self> {
        if bound == 0 || value >= bound {
            bail!("nextInt({bound}) can never return {value}, so '!= {value}' constrains nothing");
        }
        if !bound.is_power_of_two() {
            self.ignored_fraction += bound as f64 / 2f64.powi(31);
        }
        Ok(self.filtered_skip(
            1,
            &format!("nextInt({bound}) != {value}"),
            move |r| {
                let bits = r.next(31);
                let val = bits % bound as i32;
                let single_draw =
                    bits.wrapping_sub(val).wrapping_add(bound as i32 - 1) >= 0;
                single_draw && val != value as i32
            },
        ))
    }

    /// Records `nextBoolean() == value`. `next(1)` is the top state bit, so
    /// this is a clean interval.
    pub fn next_boolean_eq(&mut self, value: bool) -> &mut Self {
        // Arguments are constants here, so this cannot fail and stays
        // infallible for callers.
        let bit = BigInt::from(u32::from(value)) << 47;
        let hi = (&bit + (BigInt::from(1u32) << 47)) - 1u32;
        self.push_bound(bit, hi)
    }

    /// Adds a predicate that is replayed over candidate seeds.
    ///
    /// `width` is how many generator calls the predicate consumes.
    pub fn filtered_skip<F>(&mut self, width: u64, label: &str, test: F) -> &mut Self
    where
        F: Fn(&mut JavaRandom) -> bool + Send + Sync + 'static,
    {
        self.filters.push(Filter {
            at_call: self.cursor,
            width,
            test: Box::new(test),
            label: label.to_string(),
        });
        self.cursor += width;
        self
    }

    /// Fraction of the seed space knowingly excluded — see the field docs.
    pub fn ignored_fraction(&self) -> f64 {
        self.ignored_fraction
    }

    /// Rough count of how many seeds are expected to survive the interval
    /// constraints alone.
    pub fn expected_lattice_solutions(&self) -> f64 {
        let space = 2f64.powi(48);
        self.bounds.iter().fold(space, |acc, b| {
            let width = bigint_to_f64(&(&b.hi - &b.lo + BigInt::one()));
            acc * (width / space)
        })
    }

    /// Estimated enumeration nodes, which is what actually decides whether a
    /// query is tractable.
    ///
    /// Two independent things blow the budget, and this covers both:
    ///
    /// * **Too few bits.** The box genuinely contains a huge number of lattice
    ///   points, and every one of them is a real answer that must be visited.
    /// * **Too many dimensions.** Enumeration walks the ball circumscribing the
    ///   box, and in `d` dimensions that ball exceeds the box by roughly
    ///   `(sqrt(d)/2)^d` — negligible at `d = 6`, about 3e3 at `d = 13`, about
    ///   1e12 at `d = 28`. LattiCG avoids this by tightening each branch with
    ///   an exact-rational LP; we pay for the simpler geometry here instead.
    ///
    /// Measured against the real implementation: 6 four-bit calls estimates
    /// ~5e7 and does indeed exhaust the default budget (after 19 minutes,
    /// which is exactly what this estimate exists to prevent), while 13 of
    /// them estimates ~2e2 and completes in a quarter of a second.
    pub fn estimated_enumeration_nodes(&self) -> f64 {
        let d = self.bounds.len() as f64;
        if d == 0.0 {
            return 0.0;
        }
        let ball_blowup = ((d.sqrt() / 2.0).powf(d)).max(1.0);
        self.expected_lattice_solutions() * ball_blowup
    }

    /// Every seed consistent with all observations, with default limits.
    ///
    /// # Return value
    ///
    /// Seeds are **normalised to their low 48 bits**. `setSeed` masks to 48
    /// bits, so the top 16 of a 64-bit world seed leave no trace in generator
    /// output and cannot be recovered here; a seed of -99887766 comes back as
    /// 281374976822890. Compare against `your_seed as u64 & (2^48 - 1)`, not
    /// against the number shown in game. Recovering the upper bits needs biome
    /// data — see [`crate::multicrack::recover_upper_bits`].
    pub fn solve(&self) -> Result<Vec<i64>> {
        self.solve_capped(SolveLimits::default())
    }

    /// [`Reverser::solve`] with an explicit budget.
    ///
    /// Interactive callers should set `max_nodes` low enough that a hopeless
    /// query gives up while the user is still watching.
    pub fn solve_capped(&self, limits: SolveLimits) -> Result<Vec<i64>> {
        if self.bounds.is_empty() {
            bail!(
                "no interval constraints were recorded, so the lattice is empty — every \
                 observation given can only be checked by replay, which means brute force"
            );
        }

        // Refuse before spending anything: the estimate below is microseconds
        // of arithmetic, where discovering the same fact by exhausting the
        // node budget takes minutes to hours.
        let estimate = self.estimated_enumeration_nodes();
        if estimate > limits.max_nodes as f64 {
            let solutions = self.expected_lattice_solutions();
            let budget = limits.max_nodes;
            let d = self.bounds.len();
            // Which of the two failure modes is this? Blaming the observations
            // when the real problem is dimension or a deliberately tight budget
            // sends the user off to collect data that will not help.
            if solutions > 1000.0 {
                let short_by = solutions.log2().ceil().max(0.0) as u32;
                bail!(
                    "this system is too loose to enumerate: about {solutions:.3e} seeds satisfy \
                     it, needing roughly {estimate:.3e} nodes against a budget of {budget}. \
                     Record about {short_by} more bits of observation ({d} interval constraints \
                     so far, over 48 bits of seed)."
                );
            }
            bail!(
                "this system is well constrained (about {solutions:.3e} seeds satisfy it) but \
                 spread over {d} dimensions, where enumeration walks a ball roughly \
                 {:.3e} times the size of the box — about {estimate:.3e} nodes against a budget \
                 of {budget}. Use fewer, higher-information calls, or raise max_nodes.",
                estimate / solutions.max(f64::MIN_POSITIVE)
            );
        }

        let d = self.bounds.len();
        let modulus = BigInt::from(1u64 << 48);
        let mult = BigInt::from(MULTIPLIER);
        let base = self.bounds[0].call_index;

        // Basis rows: the LCG orbit, plus the modulus in each axis.
        let mut basis = RatMatrix::zeros(d + 1, d);
        for (i, b) in self.bounds.iter().enumerate() {
            let power = mult.modpow(&BigInt::from(b.call_index - base), &modulus);
            basis.set(0, i, BigRational::from(power));
            basis.set(i + 1, i, BigRational::from(modulus.clone()));
        }

        // The additive part.
        //
        // Writing `s` for the state at the *first measured* call `k_0`, the
        // state at call `k` is `s * a^(k - k_0) + c_(k - k_0)`, where `c_j` is
        // what a generator started from internal state 0 holds after `j`
        // steps. The offset is therefore indexed by `k - k_0`, not by `k`:
        // measuring it from the true origin instead shifts every constraint and
        // the true seed silently falls outside the box.
        let mut offset = Vec::with_capacity(d);
        let mut zero_run = JavaRandom::from_state(0);
        let mut at = 0u64;
        for b in &self.bounds {
            let delta = b.call_index - base;
            while at < delta {
                zero_run.advance();
                at += 1;
            }
            offset.push(BigRational::from(BigInt::from(zero_run.state())));
        }

        let lower: Vec<BigRational> = self
            .bounds
            .iter()
            .map(|b| BigRational::from(b.lo.clone()))
            .collect();
        let upper: Vec<BigRational> = self
            .bounds
            .iter()
            .map(|b| BigRational::from(b.hi.clone()))
            .collect();

        // Scale each axis so the box becomes (nearly) a cube before reduction.
        let side: Vec<BigInt> = self
            .bounds
            .iter()
            .map(|b| &b.hi - &b.lo + BigInt::one())
            .collect();
        let lcm = side.iter().fold(BigInt::one(), |acc, s| lcm_big(&acc, s));
        let scale: Vec<BigRational> = side
            .iter()
            .map(|s| BigRational::from(&lcm / s))
            .collect();

        let mut scaled_basis = RatMatrix::zeros(d + 1, d);
        for r in 0..=d {
            for (c, sc) in scale.iter().enumerate() {
                scaled_basis.set(r, c, basis.get(r, c) * sc);
            }
        }
        let scaled_offset: Vec<BigRational> =
            offset.iter().zip(&scale).map(|(o, s)| o * s).collect();
        let scaled_lower: Vec<BigRational> =
            lower.iter().zip(&scale).map(|(o, s)| o * s).collect();
        let scaled_upper: Vec<BigRational> =
            upper.iter().zip(&scale).map(|(o, s)| o * s).collect();

        let points = enumerate_in_box_capped(
            &scaled_basis,
            &scaled_offset,
            &scaled_lower,
            &scaled_upper,
            limits.max_nodes,
        )?;

        // Coordinate 0 is `s * a^0 = s`, the state at the first measured call.
        // Step it back to the initial state and unscramble.
        let mut seeds = Vec::new();
        for p in points {
            let Some(first) = p.first() else { continue };
            let unscaled = first / &scale[0];
            if !unscaled.is_integer() {
                continue;
            }
            let state_at_base = unscaled.to_integer();
            let state = bigint_to_u64_mod48(&state_at_base);

            let mut r = JavaRandom::from_state(state);
            for _ in 0..base {
                r.previous();
            }
            let seed = (r.state() ^ MULTIPLIER) & MASK;
            seeds.push(seed as i64);
        }

        seeds.sort_unstable();
        seeds.dedup();

        // Now replay every candidate against the constraints that could not be
        // expressed as a box. `Filter::test` is `Send + Sync` precisely so this
        // can run across cores like every other hot loop in the crate.
        let events = self.merged_events();
        let mut survivors: Vec<i64> = seeds
            .into_par_iter()
            .filter(|seed| self.replay_ok(*seed, &events))
            .collect();
        survivors.sort_unstable();

        Ok(survivors)
    }

    /// Bounds and filters interleaved in the order the generator meets them.
    ///
    /// Both lists are already in ascending call order, because every push goes
    /// through the shared `cursor`; a bound pushed when the cursor read `c`
    /// gets `call_index == c + 1`, and a filter gets `at_call == c`. Keying on
    /// that pre-push cursor value merges the two without a sort.
    fn merged_events(&self) -> Vec<Event<'_>> {
        let mut events: Vec<(u64, Event<'_>)> = Vec::with_capacity(self.bounds.len() + self.filters.len());
        events.extend(self.bounds.iter().map(|b| (b.call_index - 1, Event::Bound(b))));
        events.extend(self.filters.iter().map(|f| (f.at_call, Event::Filter(f))));
        events.sort_by_key(|(k, _)| *k);
        events.into_iter().map(|(_, e)| e).collect()
    }

    /// Re-runs the generator once over a candidate seed and applies every
    /// filter in a single ordered pass.
    ///
    /// Restarting the generator per constraint would cost
    /// `O((bounds + filters) * call_index)` steps — around 1,400 for a
    /// dungeon-shaped query where 54 suffice.
    fn replay_ok(&self, seed: i64, events: &[Event<'_>]) -> bool {
        // With no filters the lattice result already is the answer, so in a
        // release build there is nothing left to check.
        if self.filters.is_empty() && !cfg!(debug_assertions) {
            return true;
        }

        let mut r = JavaRandom::new(seed);
        let mut at = 0u64;

        for event in events {
            match event {
                Event::Bound(b) => {
                    while at < b.call_index {
                        r.advance();
                        at += 1;
                    }
                    // The enumeration already filters exactly to the box and
                    // the map back is an exact integer inverse, so this can
                    // never reject. Keep it as an assertion rather than making
                    // release builds pay for it on every candidate.
                    if cfg!(debug_assertions) {
                        let state = BigInt::from(r.state());
                        debug_assert!(
                            state >= b.lo && state <= b.hi,
                            "lattice produced a candidate outside its own box"
                        );
                    }
                }
                Event::Filter(f) => {
                    while at < f.at_call {
                        r.advance();
                        at += 1;
                    }
                    if !(f.test)(&mut r) {
                        return false;
                    }
                    at += f.width;
                }
            }
        }
        true
    }
}

/// A bound or a filter, positioned in generator order.
enum Event<'a> {
    Bound(&'a StateBound),
    Filter(&'a Filter),
}

/// Budget for one [`Reverser::solve_capped`] call.
#[derive(Debug, Clone, Copy)]
pub struct SolveLimits {
    /// Enumeration nodes to allow before giving up.
    pub max_nodes: u64,
}

impl Default for SolveLimits {
    fn default() -> Self {
        Self {
            max_nodes: DEFAULT_MAX_NODES,
        }
    }
}

/// Ceiling division that is correct for negative numerators too.
///
/// The hand-rolled version this replaces added one whenever the remainder was
/// non-zero, but `div_rem` truncates toward zero — which for a negative
/// numerator has already rounded up, so the increment overshot by one
/// (`div_ceil(-7, 2)` gave -2 instead of -3).
fn div_ceil(a: &BigInt, b: &BigInt) -> BigInt {
    num_integer::Integer::div_ceil(a, b)
}

fn lcm_big(a: &BigInt, b: &BigInt) -> BigInt {
    if a.is_zero() || b.is_zero() {
        return BigInt::zero();
    }
    num_integer::lcm(a.clone(), b.clone())
}

/// Widens a `BigInt` to `f64` for the cost estimate, saturating rather than
/// silently returning a wrong magnitude on failure.
fn bigint_to_f64(v: &BigInt) -> f64 {
    v.to_string().parse::<f64>().unwrap_or(f64::INFINITY)
}

fn bigint_to_u64_mod48(v: &BigInt) -> u64 {
    let m = BigInt::from(1u64 << 48);
    let r = ((v % &m) + &m) % &m;
    let (_, digits) = r.to_u64_digits();
    digits.first().copied().unwrap_or(0) & MASK
}


#[cfg(test)]
mod tests {
    use super::*;

    /// Records what a real `Random` actually produced, then asks the reverser
    /// to find the seed again. This is the test the whole module exists to
    /// pass: if lattice construction, scaling, enumeration or the walk back to
    /// the initial state is wrong anywhere, the seed does not come back.
    fn round_trip(seed: i64, calls: usize) -> Vec<i64> {
        let mut r = JavaRandom::new(seed);
        let observed: Vec<u32> = (0..calls).map(|_| r.next_int_bound(16) as u32).collect();

        let mut rev = Reverser::new();
        for v in &observed {
            rev.next_int_eq(16, *v).unwrap();
        }
        rev.solve().expect("solve should succeed")
    }

    #[test]
    fn recovers_a_seed_from_its_own_next_int_calls() {
        for seed in [0i64, 1, 1234, -99887766, 0x0000_1234_5678_9ABCu64 as i64] {
            let found = round_trip(seed, 13);
            let masked = (seed as u64 & MASK) as i64;
            assert!(
                found.contains(&masked),
                "seed {seed} (masked {masked}) not recovered; got {} candidates",
                found.len()
            );
        }
    }

    #[test]
    fn thirteen_four_bit_calls_pin_the_seed_uniquely() {
        // 13 * 4 = 52 bits of information against a 48-bit space, so the
        // answer should be unique rather than a list.
        let seed = 0x0000_0BAD_C0FF_EE00u64 as i64 & (MASK as i64);
        let found = round_trip(seed, 13);
        assert_eq!(found, vec![seed], "expected exactly one seed, got {found:?}");
    }

    #[test]
    fn fewer_calls_leave_proportionally_more_candidates() {
        // 11 calls is 44 bits against 48, so about 2^4 = 16 seeds should fit.
        let seed = 0x0000_0BAD_C0FF_EE00u64 as i64 & (MASK as i64);
        let found = round_trip(seed, 11);
        assert!(found.contains(&seed));
        assert!(
            (2..64).contains(&found.len()),
            "expected roughly 16 candidates, got {}",
            found.len()
        );
        // Every candidate must genuinely reproduce the observations.
        let mut truth = JavaRandom::new(seed);
        let observed: Vec<i32> = (0..11).map(|_| truth.next_int_bound(16)).collect();
        for cand in &found {
            let mut r = JavaRandom::new(*cand);
            let got: Vec<i32> = (0..11).map(|_| r.next_int_bound(16)).collect();
            assert_eq!(got, observed, "candidate {cand} does not reproduce the calls");
        }
    }

    #[test]
    fn skips_are_accounted_for() {
        let seed = 987654321i64;
        let mut r = JavaRandom::new(seed);
        let a = r.next_int_bound(16) as u32;
        r.next_int_bound(100);
        r.next_int_bound(7);
        let b = r.next_int_bound(16) as u32;
        let rest: Vec<u32> = (0..11).map(|_| r.next_int_bound(16) as u32).collect();

        let mut rev = Reverser::new();
        rev.next_int_eq(16, a).unwrap();
        rev.skip(2);
        rev.next_int_eq(16, b).unwrap();
        for v in &rest {
            rev.next_int_eq(16, *v).unwrap();
        }
        let found = rev.solve().unwrap();
        assert!(found.contains(&seed), "skips mis-tracked; got {found:?}");
    }

    #[test]
    fn booleans_are_clean_interval_constraints() {
        // Four booleans is plenty to prove the encoding, and the eleven
        // four-bit calls carry the rest of the 48 bits. An earlier version used
        // twenty booleans, which pushed this to 28 dimensions where the
        // circumscribing ball exceeds the box by ~1e12 and the enumeration
        // never finishes — the shape was incidental to what is being tested.
        let seed = 555_444_333i64;
        let mut r = JavaRandom::new(seed);
        let bits: Vec<bool> = (0..4).map(|_| r.next_boolean()).collect();
        let ints: Vec<u32> = (0..11).map(|_| r.next_int_bound(16) as u32).collect();

        let mut rev = Reverser::new();
        for b in &bits {
            rev.next_boolean_eq(*b);
        }
        for v in &ints {
            rev.next_int_eq(16, *v).unwrap();
        }
        assert_eq!(rev.dimensions(), 15);
        let found = rev.solve().unwrap();
        assert!(found.contains(&seed), "booleans mis-modelled; got {found:?}");
    }

    #[test]
    fn non_power_of_two_bounds_become_replay_filters() {
        // nextInt(24) is a modular condition, not a box, so it must not enter
        // the lattice — but it must still be enforced.
        let seed = 24680i64;
        let mut r = JavaRandom::new(seed);
        let pow2: Vec<u32> = (0..13).map(|_| r.next_int_bound(16) as u32).collect();
        let odd = r.next_int_bound(24) as u32;

        let mut rev = Reverser::new();
        for v in &pow2 {
            rev.next_int_eq(16, *v).unwrap();
        }
        let before = rev.dimensions();
        rev.next_int_eq(24, odd).unwrap();
        assert_eq!(rev.dimensions(), before, "nextInt(24) should not add a lattice dimension");

        let found = rev.solve().unwrap();
        assert!(found.contains(&seed));

        // And a wrong value for that call must eliminate the seed.
        let mut rev2 = Reverser::new();
        for v in &pow2 {
            rev2.next_int_eq(16, *v).unwrap();
        }
        rev2.next_int_eq(24, (odd + 1) % 24).unwrap();
        assert!(!rev2.solve().unwrap().contains(&seed), "the filter was not applied");
    }

    #[test]
    fn a_dungeon_shaped_query_is_within_budget() {
        // The cheap companion to the ignored test below: build the same query
        // and assert the guard accepts it, without paying for the enumeration.
        // This is what keeps the dungeon path from silently regressing past the
        // point where it could run at all.
        let seed = 0x0000_DEAD_BEEF_1234u64 as i64 & (MASK as i64);
        let (rev, _) = dungeon_query(seed);
        assert!(
            rev.estimated_enumeration_nodes() < DEFAULT_MAX_NODES as f64,
            "a dungeon query should be inside the default budget, estimated {:.3e}",
            rev.estimated_enumeration_nodes()
        );
        assert!(rev.dimensions() >= 10, "position plus cobblestone should give real dimensions");
    }

    /// Builds the query SeedCrackerX poses for a 1.15+ dungeon, and returns it
    /// alongside the floor it was built from.
    fn dungeon_query(seed: i64) -> (Reverser, Vec<i32>) {
        let mut r = JavaRandom::new(seed);
        let ox = r.next_int_bound(16) as u32;
        let oz = r.next_int_bound(16) as u32;
        let y = r.next_int_bound(256) as u32;
        r.next_int_bound(2);
        r.next_int_bound(2);
        let floor: Vec<i32> = (0..49).map(|_| r.next_int_bound(4)).collect();

        let mut rev = Reverser::new();
        rev.next_int_eq(16, ox).unwrap();
        rev.next_int_eq(16, oz).unwrap();
        rev.next_int_eq(256, y).unwrap();
        rev.skip(2);
        for v in &floor {
            if *v == 0 {
                rev.next_int_eq(4, 0).unwrap();
            } else {
                rev.next_int_ne(4, 0).unwrap();
            }
        }
        (rev, floor)
    }

    #[test]
    #[ignore = "inherently ~5e6 enumeration nodes; run explicitly with --ignored"]
    fn a_dungeon_shaped_query_recovers_its_seed() {
        // The real payoff case: nextInt(16) x, nextInt(16) z, nextInt(height)
        // y, skip(2) for the size, then one nextInt(4) per floor block — 0
        // means cobblestone, anything else means mossy, which is the
        // complement of an interval and so becomes a replay filter.
        //
        // Ignored by default because it is the worst case for ball-based
        // enumeration and cannot be made cheap: roughly 40 bits over ~15
        // low-information dimensions leaves ~2^8 lattice solutions, and the
        // circumscribing ball multiplies that by ~2e4. Adding more floor
        // blocks does not help — past about 20 dimensions the extra bits and
        // the extra ball volume cancel. This is precisely the regime LattiCG's
        // exact-rational LP exists to handle, and the price of not porting it.
        // Every other test in this module finishes in under eight seconds.
        let seed = 0x0000_DEAD_BEEF_1234u64 as i64 & (MASK as i64);
        let (rev, floor) = dungeon_query(seed);

        let cobble = floor.iter().filter(|v| **v == 0).count();
        assert!(cobble >= 6, "need a few cobblestone blocks, got {cobble}");

        let found = rev.solve().unwrap();
        assert!(
            found.contains(&seed),
            "the dungeon query did not recover its seed; got {} candidates",
            found.len()
        );
    }

    #[test]
    fn an_empty_system_is_refused_rather_than_brute_forced() {
        let rev = Reverser::new();
        assert!(rev.solve().is_err());

        // Filters alone are not enough either: nothing constrains the lattice.
        let mut only_filters = Reverser::new();
        only_filters.next_int_ne(4, 0).unwrap();
        assert!(only_filters.solve().is_err());
    }

    #[test]
    fn an_under_determined_system_is_refused_immediately() {
        // Six four-bit calls is 24 bits against a 48-bit space, so ~2^24 seeds
        // really do match. Enumerating them exhausted the node budget after
        // 1133 seconds before this guard existed; now it must refuse in
        // negligible time and say what is missing.
        let seed = 1234i64;
        let mut r = JavaRandom::new(seed);
        let mut rev = Reverser::new();
        for _ in 0..6 {
            let v = r.next_int_bound(16) as u32;
            rev.next_int_eq(16, v).unwrap();
        }
        assert!(rev.expected_lattice_solutions() > 1e6);

        let t0 = std::time::Instant::now();
        let err = rev.solve().unwrap_err().to_string();
        assert!(
            t0.elapsed().as_secs_f64() < 1.0,
            "the guard should be instant, took {:?}",
            t0.elapsed()
        );
        assert!(err.contains("too loose"), "unhelpful message: {err}");
        assert!(err.contains("more bits"), "message should say what to do: {err}");
    }

    #[test]
    fn high_dimension_is_refused_rather_than_ground_through() {
        // Well constrained (48 bits) but spread over 48 one-bit calls, where
        // the circumscribing ball dwarfs the box. The estimate must catch this
        // even though the answer count is ~1.
        let seed = 777i64;
        let mut r = JavaRandom::new(seed);
        let mut rev = Reverser::new();
        for _ in 0..48 {
            let b = r.next_boolean();
            rev.next_boolean_eq(b);
        }
        assert!(rev.expected_lattice_solutions() < 10.0, "should be well constrained");
        assert!(rev.estimated_enumeration_nodes() > 1e12, "ball blowup should dominate");

        let t0 = std::time::Instant::now();
        assert!(rev.solve().is_err());
        assert!(t0.elapsed().as_secs_f64() < 1.0);
    }

    #[test]
    fn a_generous_budget_can_be_requested_explicitly() {
        // The default limit is a policy, not a hard truth: a caller who knows
        // the query is worth it can raise it.
        let seed = 0x0000_0BAD_C0FF_EE00u64 as i64 & (MASK as i64);
        let mut r = JavaRandom::new(seed);
        let mut rev = Reverser::new();
        for _ in 0..13 {
            let v = r.next_int_bound(16) as u32;
            rev.next_int_eq(16, v).unwrap();
        }
        let tight = rev.solve_capped(SolveLimits { max_nodes: 1 });
        assert!(tight.is_err(), "a budget of one node must refuse");
        assert_eq!(rev.solve_capped(SolveLimits::default()).unwrap(), vec![seed]);
    }

    #[test]
    fn bad_bounds_are_reported_rather_than_silently_empty() {
        let mut rev = Reverser::new();
        assert!(rev.state_in(BigInt::from(100), BigInt::from(50)).is_err());
        assert!(rev.state_in(BigInt::from(-1), BigInt::from(5)).is_err());
        assert!(rev.state_in(BigInt::from(0), BigInt::from(1u64 << 48)).is_err());
        assert!(rev.state_in(BigInt::from(0), BigInt::from(10)).is_ok());

        let mut rev = Reverser::new();
        assert!(rev.next_bits_in(0, 0, 0).is_err(), "next(0) is not a Java call");
        assert!(rev.next_bits_in(33, 0, 0).is_err(), "next(33) is not a Java call");
        assert!(rev.next_bits_in(4, 0, 16).is_err(), "next(4) cannot exceed 15");
        assert!(rev.next_bits_in(4, 9, 3).is_err(), "inverted interval");
        assert!(rev.next_bits_in(4, 3, 9).is_ok());

        // And the sibling of next_int_eq validates the same way.
        let mut rev = Reverser::new();
        assert!(rev.next_int_ne(4, 40).is_err(), "nextInt(4) can never be 40");
        assert!(rev.next_int_ne(4, 0).is_ok());
    }

    #[test]
    fn the_retry_branch_is_excluded_and_disclosed() {
        // A non-power-of-two nextInt can consume two calls when Java retries.
        // We fix one call per observation, so those seeds are excluded on
        // purpose — and the excluded fraction is reported rather than hidden.
        let mut rev = Reverser::new();
        assert_eq!(rev.ignored_fraction(), 0.0);
        rev.next_int_eq(16, 0).unwrap();
        assert_eq!(rev.ignored_fraction(), 0.0, "power-of-two bounds never retry");
        rev.next_int_eq(24, 0).unwrap();
        let expected = 24.0 / 2f64.powi(31);
        assert!((rev.ignored_fraction() - expected).abs() < 1e-18);
    }

    #[test]
    fn impossible_observations_yield_nothing() {
        let mut rev = Reverser::new();
        // nextInt(16) cannot return 16.
        assert!(rev.next_int_eq(16, 16).is_err());
    }
}
